### ISSUE TITLE
Animated Model Processor is Nonfunctioning in MG 3.7.1

### ISSUE THREAD

**Issue by TiberiumFusion** [tainicom/Aether.Extras#10]
When attempting to process an FBX file as either a GPU AnimatedModel or CPU AnimatedModel, the build fails with the generic "Failed to create processor 'GpuAnimatedModelProcessor'" or "Failed to create processor 'CpuAnimatedModelProcessor'" message.

This has occurred for all my models, including the included dude_GPU.fbx in the Samples section. I've tried both the Aether.Extras "Windows" and "Portable" binaries with the release MG 3.7.1 pipeline tool.

Most interestingly, the AnimationContent sample project simply copies pre-built XNB files. There is no sample in this repo (that I could find) which demonstrates how to correctly configure the pipeline tool to build with the GPU AnimatedModel or CPU AnimatedModel processors.

**Comment by nkast** [comment]
A common reason for the "Failed to create processor" is that some of your files were blocked by the OS.
See here 
http://community.monogame.net/t/3d-model-viewer-for-monogame-ver-0-6/8696/37
and here
http://www.chilkatforum.com/questions/8260/could-not-load-assembly-operation-not-supported-exception-from-hresult-0x80131515

Additionally, in 3.7 & 3.7.1 the pipeline.exe fails to load custom importers/processors. 
https://github.com/MonoGame/MonoGame/issues/6676
https://github.com/MonoGame/MonoGame/issues/6443

Also be advised that the pipeline.exe in 3.6 will randomly wipe random folders from your disks, DO NOT INSTALL IT. You have been warned.   
The 3.5 is the only release that one can say it's somewhat stable and safe to use (but also quite outdated).

You have a number of alternatives none of which is particularly good.
- Edit the .mgcb by hand and run MGCB.exe from the command line.
- Copy the DLLs inside the root folder of pipeline.exe.
- Fix and rebuild pipeline.exe from source. ([here](https://1drv.ms/f/s!AgIeh29TX5UhkPpmkvhReh693ZeppA) is my custom build of the SDK)
- Follow the [FNA ](https://github.com/FNA-XNA/FNA/issues/126) paradigm to build content via XNA and then use the .XNBs in MG.

**Comment by TiberiumFusion** [comment]
Thank you very much for the information. Using a dummy XNA project to build content seems to be the most straightforward approach.

Do you know if these workarounds are the de facto approach for the MG community? The critical info you shared isn't headlined or noted on the official website. I rather like the MonoGame concept and approach, but it's worrying if the rule of thumb is to use a 3-year old build and/or hacky pipeline fixes.

**Comment by nkast** [comment]
I don't think there's a de facto workaround. You can search in the community forums for tips and possible solutions. My guess is that most people roll back to 3.6 and waiting for the next version.

**Comment by nkast** [comment]
@TiberiumFusion 
FYI, the Animation sample now loads the model through the pipeline. 
Also pushed some improvements and fixes with the keyframe interpolation.

https://github.com/tainicom/Aether.Extras/commit/badbde3b49cec6b9bc5c5214890fa8c562cc3073
