### ISSUE TITLE
Unable to open the samples

### ISSUE THREAD

**Issue by donkeyProgramming** [tainicom/Aether.Extras#13]
When openning the samples I get the following error:
 error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Also, tried to find "MonoGame\v3.0\MonoGame.Content.Builder.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\ole_k\AppData\Local\Microsoft\VisualStudio\16.0_b6262156\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\ole_k\Desktop\Aether.Extras-master\Samples\SLMC\Samples.SLMC.WINDOWS.MG.csproj

I get this for all the projects within the sample folder, but it looks like all the other projects are loading correctly. 
There is no monoGame folder in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild
There is a C:\Program Files (x86)\MSBuild\MonoGame\v3.0 folder, but it does not contain a MonoGame.Content.Builder.targets file, but there is a MonoGame.ContentPipeline.targets. If I change it to MonoGame.ContentPipeline.targets I can open and compile the sample projects, but I get a null reference exception inside the constructor of the Game class

Is this a bug or a configuration issue? If its configuration, any ideas on how to resolve?

**Comment by nkast** [comment]
The projects need the MG sdk. You can find it at the community.monogame.net 

For an up to date sdk you can use this link.
https://github.com/kniEngine/kni/releases/tag/v3.8.9101
