### ISSUE TITLE
System.IO.FileLoadException when exectuting Ather code

### ISSUE THREAD

**Issue by MagicGrapix** [tainicom/Aether.Extras#15]
Hello,

I need to add animations to my monogame project. I compiled the Windows.MG project of Aether and I copied all the (realease) Dlls from the Windows folder somewhere in my project and I referenced them in my VisualStudio project. When I launch the game, it crashes as soon as some Aether assembly has to be loaded. Am I missing something? 

```
Exception thrown: 'System.IO.FileLoadException' in Catrine.dll
An unhandled exception of type 'System.IO.FileLoadException' occurred in Catrine.dll
Could not load file or assembly 'MonoGame.Framework, Version=3.8.9008.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

I'm using Monogame.Framework.DesktopGL in version 3.8.0.1641. I saw the Aether project was using Monogame.Framework.Portable.9000 in version 3.8.9008.0. However, if I set this framework to my project, some fields began to be null. I read on internet that this Monogame.Framework.Portable.9000 is only a wrapper. However, I'm a bit lost.

Best regards,
Quentin

**Comment by nkast** [comment]
Hi, 

Monogame uses 'bait & switch' for libraries. You don't need to copy the Monogame dlls in the final folder. 
The repo include the needed precompiled binaries, you can what you need here: 
https://github.com/tainicom/Aether.Extras/tree/master/bin/Release/Windows

**Comment by nkast** [comment]
Another thing is that I probably have to add netlibrary2.0 versions of those libraries since monogame has moved to net core 3.1 in their last version 8.1.

**Comment by MagicGrapix** [comment]
Hello,

Thanks for the reply. I tried with the prebuilt libraries and it seems it's going further. However, I still get an error:
```
Exception thrown: 'System.IO.FileNotFoundException' in Aether.Animation.dll
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Aether.Animation.dll
Could not load file or assembly 'SharpDX.Direct3D11, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1'. The system cannot find the file specified.

```
I saw that you used SharpDX in Aether. Is this a dependency of the Graphics importer? Is there a way to not have to carry out this dependency? All I need is the animations (I'm a beginner in this domain).

Moreover, what could be the problem of this netlibrary2.0 missing?

Thanks for the support.
Best regards,

Quentin

**Comment by nkast** [comment]
I am using an optimization hack to directly update the buffers. Since you are using the GL platform you have to remove the MAPPEDMEM definitions  and the references to SharpDX from Aether.Animation.WINDOWS.MG and the references to SharpDX.

As an alternative you can use the binary from Aether.Animation.PORTABLE.csproj which doesn't have this optimization.
I am not sure if portable libraries are still supported thou from the latest visual studio or if you are targeting netcore.
