### ISSUE TITLE
How to add it in MonoGames?

### ISSUE THREAD

**Issue by MrScautHD** [tainicom/Aether.Extras#16]
Hey how can i add this lib to my project is there a NuGet link?

**Comment by nkast** [comment]
Hi, 
there are no nuget packages.

There are some prebuild libraries in /Bin/Release/. 
A lot of the libraries are importers for mgcb which doesn't work with nuget packages. 
You have to copy the dlls and add a reference in .mgcb 

The libraries are build for net4 (/Windows folder) and Portable. I don't know which one 
of those two will work best with the latest version of MG pipeline (net6). 
If it doesn't work you would need to rebuild them. 
Also some of the libraries use shaders, those will also need to be upgraded to the newer version.

**Comment by MrScautHD** [comment]
oh ok, is it possible if you release it on NuGet? Allot of players would love to have this very easy!

**Comment by nkast** [comment]
The importers will not work as nuget packages.
It's better to have all the DLLs in a folder and reference them locally.

**Comment by nkast** [comment]
@MrScautHD the library will be moved to https://github.com/nkast/Aether.Extras/.

Under the releases you will find a .zip with the old builds (net4 and portable),
See if those will work with the new MonoGame pipeline - no guarantees.  
https://github.com/nkast/Aether.Extras/releases/tag/v0.9.0

I am in the process to create netstandard2.0 projects.
