### ISSUE TITLE
CPU Animated model's texture coordinates are zero

### ISSUE THREAD

**Issue by Oblivion165** [tainicom/Aether.Extras#6]
It looks like the code doesn't exist for loading the coordinates on a CPU animated model.

                       case VertexElementUsage.TextureCoordinate:
                            System.Diagnostics.Debug.Assert(channel.VertexElementFormat == VertexElementFormat.Vector2);
                            var tex = input.ReadVector2();
                            gpuVertices[i].TextureCoordinate = tex;
                            break;

It's always 0,0. I spent a few days making blended animations on this library and then I can't even get textures to work -.-

**Comment by nkast** [comment]
>It looks like the code doesn't exist for loading the coordinates on a CPU animated model

`cpuVertices` does not have texture coordinates, `gpuVertices` is what is send to the GPU for rendering.

> I spent a few days making blended animations on this library and then I can't even get textures to work -.-

What does this mean exactly? 

FYI, this library is under the *Apache License Version 2.0*. You have to stop using the library if you don't agree with the terms of the license. Please pay extra attention to terms 7 & 8 (*Disclaimer of Warranty* & *Limitation of Liability*).
