### ISSUE TITLE
Opengl dotnet core

### ISSUE THREAD

**Issue by ykafia** [tainicom/Aether.Extras#9]
Is it possible to use your project in a dotnet core monogame project with an opengl backend?

**Comment by nkast** [comment]
The monogame backend you will use should be irrelevant.
As for the dotnet core, no, I don't officially support it yet. You have to try it ourself and see what works.

**Comment by nkast** [comment]
>> Is it possible to use your project in a dotnet core monogame project with an opengl backend?

>> The monogame backend you will use should be irrelevant.

Well, thing are a bit more complicated. This project is a collection of my shaders and importers/ processors. 

 * In the libraries with shaders I usually embed the shader in the dll, and I am currently doing so for the DX11. I still don't have a solution/project for gl shaders.

 * The 3d model Animation library in .Windows project has an additional `hack` to write directly in SharpDX buffers mapped memory (look for MAPPEDMEM definition). For the gl backend you can try the  portable version.

If you be more specific in which library you are interested I could see what can be done. 
But for a dotnet app it's best to way for monogame official support and/or the NetCore project be finalized as it is now rapidly changes.
